### ISSUE TITLE
Which countries we want to visit?

### ISSUE THREAD

**Issue by nsavchuk41** [nsavchuk41/summer_trip#1]

**Comment by DianaKuzmenko** [comment]
I assume that *SPAIN* is very beautiful in July

**Comment by DianaKuzmenko** [comment]
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxISEhUSEhIVFRUVFxUXFxUYFxcXFRUXFRcYFxYVFRcYHSggGBolHRUVITEhJSkrLi4uFx81ODMtNygtLisBCgoKDg0OGxAQGislHx8tLS0tLystLSstLS0tLS0tLS0tLS0vLS0tLS0vMC0tLS0tLS0tLy0tLS0rLSstLS0tLf/AABEIAOEA4QMBIgACEQEDEQH/xAAbAAACAgMBAAAAAAAAAAAAAAAAAQIDBAUGB//EAEEQAAICAQIDBgQDBQUHBQEAAAECABEDEiEEMUEFBhMiUWEycYGRFKHwI0JSscFicpLR4RUWM1OisvEkNEOC0hf/xAAaAQEAAwEBAQAAAAAAAAAAAAAAAQIEAwUG/8QALBEAAgIBAwMDAwMFAAAAAAAAAAECEQMSMVETIUEEImEUMoFScfAFkaHB8f/aAAwDAQACEQMRAD8A3dQhUNM1HzIFYWIVArADVC4oQADR3FFUAZgDCEAYaPVIERQSXLkl+LLMMGWKZBKZqO+eEkI4QED4sn7wv4VP9nnv6/nyk9ICh1KMLVgQR6gzne2+7SY0bLjZtKi9GnV9mvYfP0mbLjd2jfiyJqjmYQhOB3CEcDAFCEDAARRwMABJKOnWREyOC+LmBQN2a5gjb1O8AtVNI25kbn09h6bc5UwAk8eQMSAOhI52a3689r6SJ36QVK9XvCS1n1WEgHbXAGSIiqekeSKPVCAqAGqO4XDaAK4rMnY9IiYAriuSigDBjqRqIwCcAZEQqAXY2h2rgL4m0EBipTdtIKvsRvsTdVdfMXI4xMbvPkrhXH8RRf8AqBP5LOc/tZowfcjiMuNlYqwKsDRB2IPuJGZXE5S6IxNsg0G+dWSh99rX20j2mLMRvC4QigkdxNGB6yN3AJNE3rDnFkPQQCUQFR1cF9ft+vpALOGI1DV/lXoSR0+U2GQkE7AGze3M9efL5TC4bCGsajsLoAEkbDmTy3H3mQ/p6AD6AAfXlIZWQax6L9l/yhFpjkFbOvijhU9M8sUKhcBAGIVGFlq4rkEpFVQqZIw9Nr9Ov2+hkjw8WW0MwwIVMs4YvC9oI0sxYplHDI+FA0sx47l5xReFApkccw+9OULw4BUNqcAWTsdLeYV1E2eLHOf785t8WP0DOfrSr/JpzyuomjBH3HLQhCYzcEIQgBUDcKiPvAETFphJQANfr+kQ9PnJGREAv4ZbYbkX6EjauV+/L6zMY2brnvQmtv0/VTN7PbLkbSoL6dzS6mq+X19T7yCrRbUJkf7L4j/lN9oRpZS0dLDTDlC56R5gUIwsVmTSCSZZFGpmCgdSaE1+XvLgC0viWdrCra+/m2JEu7Z4IZcR5gr5hQ1H3GkfEa2HznGZ8DIxVtiOY2Nfba5myzknSNuHHFqyPEZSxJYkkkk2bskVZ+w+0zuH7d4hECLk2FAWFJA+ZHKa0xMZwTaNNI2p7xcV/wAz/pT/APMWDt/iVv8AaXZs2AfbbbYbchNUSfeKzJ1PkjSjpsHe5xWvEjf3SVP53Ls3e4V5MO/9prH2A3/KcmYx85PUlyR048HT4u9xDHXiUrtWkkEeu5+L8pd/vamr/gto9dQ1fUcvpc5Gt4X6x1JckdOPB3T96uGA8odj6aar5/6XynK9scY2fIchrfZQNwAOQv6k/Wa+5YMzVV2B0O4/P9bxKbluWjBR2IyeLEzEKqlieQAJJ67AQ8ReoI9hyP1PL85te6vHY8HF4czsdCMxNKxbzIyjygc7boZQsl3NcODyFvDGNy/8Ghtf+Grhj4PKyl1xuyrdsEYqtbm2AoTuf96+ETJ4+vK+VcOLAGRNAoZC7lRlZ2UfCDqJO5k+E7xcLhtk8XRk4jLnQjUoQPiCW+MEeKgyhl08qo9JalydNC5OCXg8pUOuLIVJoOEYqSTQANVd7VLE7H4gsF8DKCehRl25WSwAA9+U6TJ25gY8Pk/E508IcMrcKqMcP7F1LOCHC6SF1AFbsD6dD2Z2xgz58zLmdlfHVaMg0ftdXLJla75HTpHlG0lRTZDiktznuye59DxOIsgfuLekf3nH8h95Lie56izjZrBBKv8ACFJ5EgWNiKM7D/aSKBbP5FyJoA8mTVqpjvtzBII5iRzdsYnDqwItcSq4G+gFC4YXzBDEH3nbpqtjO5L9Rw3afdTIiXjGogA35g+Sz0Sq2vmG5DlObzY2Q6WDKdtiCp35bGet9qdqY8o8oYFWNXVaCOQrkBQ29zNb4g50L26b7cv5n7yHhvYrLMours4nsLsM52JcsqCjek+ffkpO3LrfptO1wqmJQmNQqjoP6k7k/OLJmMpJnSGNRM+TM5F3jQlGmE6UcdTK4RRySgCSWQqSWAZvDNOH7ZyK+VyAFFkC+Z350P6/cztuHnB9uY9PEZB6MTZsnfzA/mJmz7I3en8mIygGvT7bRqhO4Un5AmI52/iIHpyHvSjYSGRidz9P9JnNQPfUVHJruvIihV3sTd1X1P6qQEAKhAwEAIrjqRqAO4RGSWARqZPZnEeFlXJZFatwAT5lKnYkXsxHMHfYg0ZRUKgG+ftbhtj4ZNhiQVViG8Z3VzkY63OnSNJYimrVYuGXvBisaMIALYi4KY6ZAxOVQDdatX+s0OjrNr3a4DHnysuQWAhYbkbggdPnKZsyxQc5bI641LJJRXk1TZ2PxUfUVQJ9bFH85tO7OU/iEtit6qoCia3WugIvce02/Gd2sbeXH5CepLEADnt12mf2b2Pi4fced6rWeY/uj90fn7x6TKvUR1w2+SnrMb9O9M92vBl5jKDLHaQnpnjsWqPXI1CoKk/FiuRAgJIJwiuOAVwBjmbj7OJfCmoftgCDXKyRv6/DIstGLlsYQjWbEdknRjfX/wAQqBSsVGptNFxsCOoNS3N2EyPRdQNLuWKsCqoQCdJFnciq53I1I6dDJwYfDzlO+mMDODVasakn+IgkfyCid7h7JamZWDAKjrQILq+rkDuGGhtp533uRl4zMrNqKNpB6VpFAA8uf85xzSVGrDjlHu0ac1JYUBO/L+fp8pEiveWYOdnku59v1+iOczGgHe/1y+XpFI36RgwBwkdV/r/OIC4AB/XYda511r1M6z/cw6yoy2HzYceBgu2VcieK+TnsEx79bO205QCp1Ay8YPDXFxdrhXwsDVjFjNrXTgZdYNjAQGLBl2HlsiSi0a8lfaHdgYjmrISicOnEY2KafEV2VaYE+UglvXl7y3he6yNw+DO2Vx4zItBEKrrzDDuS4Y872WW/i+0UCk8V0ZQ2RVakIy5si5Dmxl9vw5O4Ncgek1vE9vcajeE2dTpbUKxYKBLeKGU+HYBJ1VtzquknsWeleDcP3EZWo5gF8ZkDhbVsS4myNkABvUCjJo9RzmoHZGLLjzZOGyvk8P8ADhVbGELPnyHGF2Y+gN/2q6Sh+3uLQIVzmjlfOpAXy5msZD8O3xta/Cdd1vMrsvtnj8+YBMoUnQWIxYNKLiYsrV4dWGYkepP2dmQ3A2nFdxAjC85bHTAsF0t4iMVZQDY0igb639Zm8L2XiwG8I0miCWtiwNH1Fcuk2fEcW5UIXZgN/MdRuqvUd/pde0j2TwZzZVTpdsfRRz/y+s7SwQlBxmrTMjzy6i6Xbgr7S4Q4sunXq0gXtXmZbI5+8w3abXvPgZeJcn96mB9qr8qImr0y2DDDFDTBUjl6vNky5W5u67fgquKWlZAzsZSNwkqkSJJASQkZNIJJ1FJVCQTRRc2+PiMwRCBjPh6SrFAGUbuPOwArY3R6+81FSfiMKN8hQ6iqqqOxFQ0Wxz0mxx58yIVAxrWlif2YdhiyAC6Pm8wAvrXMyxeLzlhsg3cFaQKxyMQ4YH4rOM/4ZqzmY8zdgj6MdRH3N+0ysHFvdmiarcVW5NgLQu2bcjqfUytHaOXxbMjtTtHLiwvmJApcegAAAFCfDCgcqLcvQzzXtTj3z5XzZK1udTUKF0BsPpOo7zYuJz0qAtjG53QAvvv62AefWcpxnCNibS4357b7TDPPCU3BNWvB6CxzUNVOuWUKtmtvn0+vtLQmm7O9EVv12N2PS/ylUuKkjrYAseo5D8v+24KlcAsdH0MCh63ADaEejpURX5wBj2mYe1c9MDmyHXp1EsxJCBwBd3X7V9veYQElAstzcdlb4srtz5sx5hlPM9Q7j/7N6mY+RydyST6k2dhQ/pJyLCBZsu7vCrldsTnykatN1uCBYPTYkH+9O57F7CKY28HGSCxtuZJHL3oXX3nmmFyrBl5qbHPmPcT1vguJXNwp8I14Y8RK28h+NfajufeVxYp9fqavbVV/s6ZMmN4Onp93Jjr2PnckDGwIF0wIv2BO1+0wAXxNRBUgglTY5GxYmfwPbOXEWIZnJFAMzFV356b3O3tKOG71ZsjOA2oKaJZE0E72FNWaqehbs82sbVpu0ZfeDC+psyhnxMQysNwNdWNzS7+s5Lje0c+FwcqKcbWAqbnV0BJFk/KdNxnab5MZxlMQujqVKIIIIOx9prcuMOVOSmKEFdiAD61fMTLkXqerFQrR55NcZek6cpSvW9hZsAyIA4IsAkBiCDXK1PS6kMGHQoXUzVe7G253uevp9Jks8rM2V3s81y7UQMBJaZGpJQCI1EIxBJO4R3FIJspJhcUcFQBEtxNKhJKYJRlo/kJIPxEXRq+dX8pxfebIDm2N0oB9jZNH05iej8U2jFgx+q+IfnkO32AnmHbpP4nLZs6zv/L8qH0njr+nwxZnmTdyb/ye/wDXSnhWCtkijs/Lpy43JChciMSVLqArA2yjdhtyHOekDvPwgzeJ+JPnw5QfNxBxq5y42AxsU1rYDEiqWgBPM+GfS6N/Cyn4dQ2IO6kjUNuVi/UTouJ47hiDqLMWZw/l1Oax4gpRmfyqH1EaixOkgmuepM5wlRtMPeLCBkd8uvPw7524RqchhxIrcsoPkYk+arkeN7Q4XPw5wniVxnRwe7JlIvDiZXHlXmCZqe0O0OHVSMeLzhSQHRdGs6KbStL8I9Bz3HOaTjHQ5HOMEIXbQDzC2dIP0qLDnR2nAdpcKvE8JxJ4pR4fDpidNGXUrDh2QnUFr4iBtfOc73q4xcvENkTL4ilUo27VQorqyKrHezy/emo0mSVJDZVztUK4CMiJj0EgqFmBij+cAv7P4N8zhMYF8yTyUDqfbcTv+5fZa8NmUFi5yWjnktNdAL9tzv8AK6mt7q8IMeHxNtWTfoaUbAX+dTf9iqW4jH7NqPyXc/ymnHjVWzPLI9aiuTW5bUlfQkfY1N+MPDt4aE4wSuFrAYEDTqy62+E2Aa62ZoOJyanZuhZj9yTN8eBx1j1Y0VT+G0sCbyM7IMikXuKLbgCp1kc/Tq9VJP8Af8kc3BYnZjj8M68LaQrDSuVXQbE1Wx6+pi4bhcAxJ4ukOhyO4sEuuNiCmx53o+hMjx/AqOJxJ4aqjOBspXUNYBBt2vbrtz5SziOzcJx5Djos5RsY/gVnVNJ99RcfSVs7ae7eldv+8Fq8DgvICcQ8TI647aiiqCFKD11kD5CcybH05zp37LwHJj0BGUM2NwratXkJVmo+U2rfYTWnsnIMDfsicq5N9xejw79eVyYs55sUnstr2/BqQ0kWnSPwOLbyIMerB4eQNZy6mUOCNW+xPQVUH4LCWFIjMVzaVUsMbsjKFQ6jesDUSARdSdaOf0kuUc1cYadBwHZ6anbOmNASiBS+lQSAWZbJ3Ao1fUzScRw7IzIeakg/SWTs5zwygk35Ia/1tCRr2hByIXGI4pJAqjAjMjcA3vb7VnYcgqoPkAgP9Z5xxvA8RldsowvTsxHlo7nby8+U9E7VU5FTiU3BVVyV+66ijfoCKmLgwZGXWqMy+qgmj71ynKUFJdzbrcZuld9/weecPwGZsgRcbaweorTXUk8ptz3R4gnbRuaUBrO/IbgD06zteF4LNk+FDQ6nZR9TtMj9li38TxMoojR8CsDYLMfiFjkJz6KOqyN932XycH3o7t5OH/bF0dHdgdBvw2NkI23oDRG3l+U58T0Tv+jjhwqBFxnRletVveyabulBY7fLeedEzMlJL37/AAaMmjV7NiUm2NgNWk6TsCQQv3mRw3Y/EZgDjxMQao7AG+VaiLHuJ33+xWKDBxAXDa0W1AgbD4auvbUB/Scs0ssXFQhdvv8AHydcOPHNScpVS/ueaVL8HDZMlnGhYDmRR/R9p2//APPsF2eMXTv++t+1eX+ktw9m4+F/Z4HOVDuWYAEE7HoLG3OX9Qs0YXjjb4K4FicqyypHBdn8G2XIuMbFjW/StySPYAzveF7Nw4V0qgJ6swDMT7mvymXwfY/BI75VzOrvz149Wn+LTp5Wd+syWwcKPiz5H9lx6T92M2YoUrku5jzPvUWq/dGBgx6mCAqtmheyi/kJueM4L8HiY6g2XKCgoUEX98j1PIXtzmIO00x7cPi0H/mOdeT6dF+kxs2d8mkOxbSCATudySb9ef5CdaZwUoxT8y54MALM7FweNhdKNhYDqN7QHUxLD940KU7cpXmZMY1ZGCjlZ2v2HrMFu3uFH/yX8kf+oiUlyVxwfFmzTgsWw1Derpl6viF1XlNM+x/hPpKMnDL0GxANGiQTzF0L+wmtbvRw4NVkI9Qor7Frmtz968uo6EQJWwYWRvzNEfaUeWK8nXpOXijpPw19I/wo9B9pxvFd4OIcg69FcgnlHzPU/Uygds8R0zOT85XrrgfTfJ3Bwe3P25xjB7Tnezu9jKpGVfEYcmFLt6Nt+cwOJ7zcS90+kE8lUChtsGIv13uS80aI+ndnY4Ar3oZWo6TpINEdDXI+0ZVQ2jUuqrC2NVeunnW35TzrBndDaMyHbcEj/wAwz52c6ndmb1JJO3oZTr/Bf6dcnpH4cwnnX43L/wAx/wDEY5PX+B9OuTtriuFwmkwDBj+kiTFcAyuD458J1Y2Knr6H5jkZt+D70OivapqNaaUKL3tmrn02mgkalWkzrDNOH2szOL7Ry5f+JkLexO3+EbflKFaVSxBJKOTbtm8wHHnxDDlIVlBClvgZG5o3p7GYPAdyez2cpkzAsLIRM6k6VHm1CtVD1uU5Mwx42yNyUE/P0H1ND6zzv8S9s2oguGDEbEhz5h8jM+VpHo+nlato9gzcbjw2vDrXTxDuQOVIOQE1PEOSASSSbJJ5mz/pNF2J3lR1CcQQrivP+63z/hP5TbcT2jw4Ck5sfLowPNjvt035zpGUaOWRTfYDNn2L2YM2otqoaVGmviY89+gG5mkXtXht/wBsm3r7fw/xfS5ndkuvEYiyFius7WdII21VVBiN9ypojn0lyT2ZTFjeq2rMjJ2aQuOw1s7o/oNLhR09zMzi+xERczBiQqk499zoIGTVt0JAkBw+Xf8Aa5gKJNs4G13qGva9Ng9bnO95+0iuNlxZX1alVzbAacwyNSm978Ik/Q8+VZTryd44o/p/n87nV5+ycKOVo0FdrOQD4F1eYlQF+e/Wa7tjhipTFw5rI/EYcLWQxxDJibK/sWULfy6TzrN2lxDAh+IzuCCCGzZGFMKYEFtwRsR1iHaOfas+YVy/a5NqBUV5tvKSPkSOU4vKdVHHwbfv52OcGVGBylMikjxTbhlYhgfb4SP705kqJe2ZioTWxQWQpJ0gnmVW6BPrK9M5t2WdX2Ibf+I6/W8mBHIIK69oj+vSWXFAIfWFSWiL8v5mAKoR6oQBWfWElqigHdwhHPRPHIxiO4jAHpijAkwkEkAs3XYvApkTIG2YlFxsboMQ539jpA+s12PFMgtjxqTk0A1tqIBNWdKgsCSTpqg3yHOVk+x3wR93dWbTtHgeFPxqhwBMZOvJ4aszOQDrJG9I7Vf7o9ZxXavdJ0wZfCxF2w8VlDON/wD04wo6E2a5NdjeYvanZmF8mfI+VQ4GQ0cuIsGTxNAAVTqB8NBpsEWOdia7tXs7hl1nEQWVjVFCpU5cqgIBvsERrs/H8icknZ6dJLY69+6XDDFhRyi5cTcOeJIyW+nKayhkvyBdaeYgbWZJ+6SHLhZ8OPBjV8pypqyg+DiGrUz5HIKmlGta+PntPOhiHoKH6+kGxj0+QAlbXA1rg3/e/sxMOZGxBRizY1dAjeIikDTkRX/epgd/7QmkxEqQwsEEEEbEEGwb+cEQc63gx95Uq33LsDFvKeW9evU172envHK8AIYEc7EuNDlygqyFQjhUgghERJSJMksAgZDVACAO5EfeTK3JQCAEGWThUAgMfvDRLKlvDYQxo8gLP8v6wCjTCbL8On8I+7f5wkFdSOlEcjcJ6R5JK4SMsxiCSSLHxXFY8K6sjAei/vNX8K9eYi4vjEwprf6L1Y+g/wA5xXaXGvncu3yA6KOgE45MmnY04cN92bnje9jcsKaf7T7n6AbD85z/ABGd3bU7FmPUmz/4kIiZmlJy3NkYqOwid994A9IpIL+jKlhmImh+r+sek/aNVgDxrtv1hUbPIA+sAmDW46b/AGmTlWmI9zMTVMlW1AVzA3HXbr7ivtBDImRMGP6/nIgXIAiZCpZUJJJELJRQgDuBihAGIwJESVwByzBk0sD9/kdjKoQDd/hj6iE0kJFEUjtIQgZ6R5AxMnCsx0lnFcR4WJ8gFlRsPc7D6WZVukXhG2aXvhnUlMYO62W9tVUD77H7znI3ckkk2TZJPMnqSZGYpSt2enFaVQoqj0RhhKliIElsP1+tpE5fT9fKIqesAV3zuv194wL9YxQk7gEAvtLseGxZIAPSiTtt8pkDGABYF9eZo3y516RF/wBAAD8oIsqbEP4vyMeNKB82+1bH68+XTeSYRQRZELCOKQSRMUZhJJFCEIAoGOEAUYgIQAuOKEAcIrhAO30wqEN56J45NBKe3/8A2uTn+7+TKd/QbS5JnIVVSzfCASb5VW9/SUkrTO2L7jzJj7iR1k8hLSBZIFf09oFgJhPSK2O25qNQIy/oJHeAO/QfWRonrGTGPaAMCTTGTyBPyFy7Hw+3msew5/6S4+nQch0EgiwN0NW7dSefPYH3/wA66SEkZGCojFGYoJERFGZGCRGRMlFJJFCEIAQhCAAgYQgBCEIAoQhAO3k1hCeieOTxyPbv/tcvyH/cI4Sktjvh3RwDcjBuf2/nFCYT0BHmPnJwhBID+pgsIQDZZ/ib+8f5yBihKlGRaIQhJQIwhCCRGRhCCRGKEJJIRCEIAQjhAImOEIAjCEIBXCEIB//Z

**Comment by DianaKuzmenko** [comment]
I found a cool trip around Spain!  Look at this!
![завантаження](https://user-images.githubusercontent.com/22542471/55622629-63628000-57a9-11e9-9b36-0c545c01e1ac.jpg)

**Comment by DianaKuzmenko** [comment]
@nsavchuk41 Do you like it?

**Comment by nsavchuk41** [comment]
It may be better to go to Greece. there is also very good at this time.

**Comment by nsavchuk41** [comment]
But if you want, then we can go to Spain too.

**Comment by DianaKuzmenko** [comment]
Greece is closer, so let's go there for the first time.
We can move there through Bulgaria and stay there for 3 days, f.e.

**Comment by nsavchuk41** [comment]
let's spend more time in Greece.

**Comment by nsavchuk41** [comment]
And we will go to Bulgaria next year.

**Comment by DianaKuzmenko** [comment]
It's a **VEEEEEEEEEEEERY** good idea
