### ISSUE TITLE
 What places would you like to see?

### ISSUE THREAD

**Issue by nsavchuk41** [nsavchuk41/summer_trip#4]
I suggest to visit:
1. Museum of the Athens Acropolis
2.National Park White Mountains
3.Theater of Dionysus

**Comment by DianaKuzmenko** [comment]
Ok! )
Also, we can join La Tomatina (Tomato Fight Festival) )))
It should be fun!)
![tomatina](https://user-images.githubusercontent.com/22542471/55625218-cc012b00-57b0-11e9-8bd0-99e69d7afdb4.jpg)

**Comment by nsavchuk41** [comment]
Perfectly!!!)
