### ISSUE TITLE
Put your best photos here!

### ISSUE THREAD

**Issue by DianaKuzmenko** [nsavchuk41/summer_trip#8]

**Comment by nsavchuk41** [comment]
❤❤👙👗👓🎈🎈🎉🎀

**Comment by nsavchuk41** [comment]
![завантаження (3)](https://user-images.githubusercontent.com/48761714/56023404-6cf26780-5d16-11e9-894a-ade13824aeb5.jpg)
![завантаження (2)](https://user-images.githubusercontent.com/48761714/56023417-74b20c00-5d16-11e9-83e0-15d466ed1bac.jpg)
![завантаження (1)](https://user-images.githubusercontent.com/48761714/56023423-77acfc80-5d16-11e9-83b7-539ffea6d847.jpg)
![завантаження (4)](https://user-images.githubusercontent.com/48761714/56023475-93b09e00-5d16-11e9-9217-96447c88f362.jpg)
![завантаження (5)](https://user-images.githubusercontent.com/48761714/56023477-957a6180-5d16-11e9-814f-225883b8fc17.jpg)

**Comment by DianaKuzmenko** [comment]
Close #4

**Comment by nsavchuk41** [comment]
![завантаження (6)](https://user-images.githubusercontent.com/48761714/56023551-c3f83c80-5d16-11e9-80e7-accc5b808e13.jpg)
![images](https://user-images.githubusercontent.com/48761714/56023555-c5296980-5d16-11e9-8c85-b83cca478e67.jpg)
